apiVersion: v1
kind: Service
metadata:
  annotations:
  name: tomcat-test
  labels:
    app: tomcat-test
spec:
  type: NodePort
  ports:
  - port: 8080
    name: tomcat-test
    targetPort: 8080
    nodePort: 31656
  selector:
    app: tomcat-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcatdeployment
  labels:
    app: tomcat-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-test
  template:
    metadata:
      labels:
        app: tomcat-test
    spec:
      containers:
        - name: tomcat-test
          image: ergho/webapp:v1
          ports:
            - containerPort: 8080
