apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: bitminio-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /minio
        backend:
          serviceName: bitminio
          servicePort: 9000
