- hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: Ping this computer
      ping:
      
    - name: debug
      debug:
        var: ansible_kernel

      docker_container:
        name: demo
        image: demo
        state: present