- hosts: localhost
  gather_facts: true
  become: true
  tasks:
    - name: Ping this computer
      ping:
      
    - name: debug
      debug:
        var: ansible_kernel
    - name: docker-py
      apt:
        name: docker-py
    - name: Create a data container
      docker_container:
        name: demo
        image: demo
        state: present