apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kiali-test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /kiali
        backend:
          serviceName: kiali
          servicePort: 20001
