---
- name: Block Google Chrome
  block:
    - name: "Check if Docker is installed"
      package_facts:
        manager: "auto"
    - name: "Debug packages"
      debug:
        msg: "{{'google-chrome-stable' in ansible_facts.packages}}"
      tags:
       - never
       - debug
    - name: install chrome
      apt:
        deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      when: "'google-chrome-stable' not in ansible_facts.packages"
  tags:
    - chrome