apiVersion: v1
kind: Service
metadata:
  name: demoapp-test
  labels:
    run: demoapp-test
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: demoapp-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deploy
  labels:
    app: demoapp-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp-test
  template:
    metadata:
      labels:
        app: demoapp-test
    spec:
      containers:
        - name: demoapp-test
          image: simonbrgstrm/demoapp:test
          ports:
            - containerPort: 8080
        - name: north-test
          image: simonbrgstrm/north:test
