pipeline {
    agent any
    stages {
         stage('Install') {
            steps {
                sh 'npm install'
            }
        }
         stage('Test') {
            steps {
                sh 'npm test'
            }
        }
         stage('Build') {
            steps {
                sh 'npm run build'
            }
        }
         stage('Copy') {
            steps {
                sh 'scp -r build/* simon@192.168.122.32:/home/simon/myapp/build'
            }
        }
         stage('Build image') {
            steps {
                sh 'ssh simon@192.168.122.32 "docker build /home/simon/myapp/ -t simonbrgstrm/myapp:test"'
            }
        }
         stage('Push image') {
            steps {
                sh 'ssh simon@192.168.122.32 "docker push simonbrgstrm/myapp:test"'
            }
        }
         stage('K8s deploy') {
            steps {
                sh 'ssh simon@192.168.122.32 "/snap/bin/microk8s.kubectl apply -f /home/simon/eshop/myapp-deploy.yml"'
            }
        }
    }
    post {
        success {
            echo 'I succeeded!'
        }
        unstable {
            echo 'I am unstable.'
        }
        failure {
            echo 'I failed...'
        }
    }
}
