---
- hosts: localhost
  gather_facts: no
  vars:
    docker_network: fun_network
    db_name: db_server
    tomcat_name: tomcat_server
    tomcat_host_port: "8080"
    tomcat_container_port: "8080"
    MYSQL_ROOT_PASSWORD: hej 
    MYSQL_DATABASE: northwind
    MYSQL_USER: northwind
    MYSQL_PASSWORD: hej
    

  tasks:
    - name: "Create a network"
      docker_network:
        name: "{{ docker_network }}"

    - name: "Launch database container"
      docker_container:
        name: "{{ db_name }}"
        image: ergho/mysql:v1
        restart_policy: always
        network_mode: "{{ docker_network }}"
        env:
          MYSQL_ROOT_PASSWORD: "{{ MYSQL_ROOT_PASSWORD }}"
          MYSQL_DATABASE: "{{ MYSQL_DATABASE }}"
          MYSQL_USER: "{{ MYSQL_USER }}"
          MYSQL_PASSWORD: "{{ MYSQL_PASSWORD}}"

    - name: "Launch tomcat container"
      docker_container:
        name: "{{ tomcat_name }}"
        image: ergho/webapp:v1
        ports:
          - "{{ tomcat_host_port }}:{{ tomcat_container_port }}"
        restart_policy: always
        network_mode: "{{ docker_network }}"
