apiVersion: v1
kind: Service
metadata:
  name: strapi 
  labels:
    run: strapi 
spec:
  type: LoadBalancer
  ports:
  - port: 80 
    targetPort: 1337
    protocol: TCP
    name: http
  selector:
    app: strapi 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi 
  labels:
    app: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
        - name: strapi
          image: strapi/strapi
          ports:
            - containerPort: 1337 
