image: node:13.7

cache:
  untracked: true
  key: "$CI_BUILD_REF_NAME"
  paths:
    - node_modules/
    - .yarn-cache

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - yarn config set cache-folder .yarn-cache
    - yarn install --pure-lockfile
    - yarn build
  artifacts:
    paths:
      - build

test:
  stage: test
  script:
    - yarn test
  dependencies:
    - build

# needs to be called pages for gitlab pages
pages:
  stage: deploy
  script:
# gitlab pages uses public folder for deployment
    - rm -rf public/*
    - mv build/* public
    - ls -al public/
  artifacts:
    paths:
      - public
  dependencies:
    - build
  only:
    - master