apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress01
spec:
  rules:
  - host: z-enterprise.com
    http:
      paths:
      - path: /
        backend:
          serviceName: webapp-service
          servicePort: 8080
