{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cmt20.serviceAccountName" . }}
  labels:
{{ include "cmt20.labels" . | nindent 4 }}
{{- end -}}
