apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cmtapi
  name: cmtapi
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cmtapi
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: cmtapi
    spec:
      containers:
      - command:
        - python
        - app.py
        image: localhost:32000/cmtapi
        imagePullPolicy: Always
        name: cmtapi
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
