apiVersion: v1
kind: Service
metadata:
  labels:
    run: cmtapi
  name: cmtapi
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: cmtapi
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}