apiVersion: v1
kind: Service
metadata:
  labels:
    run: cmtapi
  name: cmtapi
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    run: cmtapi
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}